### ISSUE TITLE
Error to bind Magic Gate

### ISSUE THREAD

**Issue by biagioDO** [israpps/FreeMcBoot-Installer#20] opened 2023-03-07 13:46 UTC
Hi, I try to install FMCB on a 256MB Memory Card, but I have the error "No Bind Magic Card" (or something like this, I don't remember the exact error message). 
There is a way to install FMCB?

thanks

**Comment by israpps** [comment] 2023-03-07 13:55
> Hi, I try to install FMCB on a 256MB Memory Card, but I have the error "No Bind Magic Card" (or something like this, I don't remember the exact error message). There is a way to install FMCB?
> 
> thanks

Hi.

Unfortunately, that issue has no solution (other than replacing the card with a decent one)...

this issue arises because your card can't respond to the card ID request issues by the mechacon...

that card ID is part of the encryption procedure, Sony made it to ensure binded updates are unique per card...


As I said, this has no solution. because the problem resides on the controller chip inside the card

**Comment by israpps** [comment] 2023-04-21 18:03
closing as not planned as this is not an issue. and something we cannot fix because the problem is the memory card

**Closed by israpps** 2023-04-21 18:03 UTC
Labels: Not an issue
